# Window settings
show=dmenu
width=1280
height=800
location=center
show=dmenu
prompt=Select Wallpaper
layer=overlay
cache_file=/dev/null

# Layout
columns=5
image_size=250x141 # 16:9
allow_images=true
insensitive=true
hide_scroll=true
sort_order=default

# Style
stylesheet=wallpaper/wallpaper.css
