# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    kernelModules = ["kvm-amd"];
    extraModulePackages = [];
    initrd = {
      availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
      kernelModules = [];
      luks.devices."luks-0ab0e28a-8209-4391-9a4f-dc1240c8bea4".device = "/dev/disk/by-uuid/0ab0e28a-8209-4391-9a4f-dc1240c8bea4";
    };
  };

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/1f668d89-2f36-4347-9a72-1c6cfd2fd9e9";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/B2B2-768D";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    "/home/stefan/extra" = {
      device = "/dev/disk/by-uuid/bb11e84b-ea33-400c-9e41-1c735203d973";
      fsType = "ext4";
    };
  };

  swapDevices = [{device = "/dev/disk/by-uuid/8f8a291d-e4fd-4f77-85a1-9dc1e744a0d0";}];

  # https://nixos.wiki/wiki/Power_Management
  # /proc/acpi/wakeup -> GPP0, GPP7, DP40
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x1022", ATTR{device}=="0x14db", ATTR{power/wakeup}="disabled"
    ACTION=="add", SUBSYSTEM=="pci", ATTR{vendor}=="0x1022", ATTR{device}=="0x43f5", ATTR{power/wakeup}="disabled"
  '';

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
