#!/usr/bin/env bash

set -euo pipefail

(($# == 0)) && {
	echo please provide an rdp file as argument
	exit 1
}

# change display settings
sed -i "s/desktopwidth:.*/desktopwidth:i:2556/g" "$*"
sed -i "s/desktopheight:.*/desktopheight:i:1392/g" "$*"
sed -i "/smart sizing/d" "$*"

# start xfreerdp with the rdp file
xfreerdp "$*" -grab-keyboard
