# Edit this configuration file to define what should be installed on
# your system. Help is available in the configuration.nix(5) man page, on
# https://search.nixos.org/options and in the NixOS manual (`nixos-help`).
{
  config,
  lib,
  pkgs,
  ...
}: {
  imports = [
    ./hardware-configuration.nix
    ../../system/greetd.nix
  ];

  nix.package = pkgs.nixFlakes;
  nix.settings.experimental-features = ["nix-command" "flakes"];

  # Use the systemd-boot EFI boot loader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "stefan-nixos";
  networking.networkmanager.enable = true;

  # Configure network proxy if necessary
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  time.timeZone = "Europe/Berlin";
  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_TIME = "de_DE.UTF-8";
  };

  # Configure keymap in X11
  services.xserver.xkb = {
    layout = "de";
    variant = "nodeadkeys";
    options = "caps:escape_shifted_capslock, compose:sclk";
  };
  console.useXkbConfig = true; # use xkb.options in tty.

  # wayland-related
  security.polkit.enable = true;
  # hardware.opengl.enable = true;

  # Enable CUPS to print documents.
  services.printing.enable = true;
  # Enable sane for scanner
  hardware.sane.enable = true;
  services.avahi.enable = true;
  services.avahi.nssmdns4 = true;

  # Enable sound.
  sound.enable = false;
  # nixpkgs.config = {
  # allowBroken = true;
  # allowUnfree = true;
  # };
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    # If you want to use JACK applications, uncomment this
    #jack.enable = true;
  };

  # automount / unmount drives
  services.devmon.enable = true; # automatic mounting of drives
  services.gvfs.enable = true; # userspace virtual filesystem
  services.udisks2.enable = true; # DBus service for applications to query storage devices

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.stefan = {
    isNormalUser = true;
    extraGroups = ["wheel" "audio" "video" "scanner" "lp"];
    # shell = pkgs.nushell;
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrOG3FrTlVDOj5TTe5njEB5JUgJ8jum7GdXGK3wNTMeqogCBd1X0K7vTCw2GikgWeUzjN1BM4WeSIlcjyQWGePIVzUlFUhj98h3N9jsQ6T1W7Gyq6vOF35w3cDQTmLYHgFWeDl0llJzj8PW4iJGhVClaVZSyhEVhc78d8xOLadaDK9IljIHaULgDYcZg4Gx+TwcnNmYRvg9oY5RdPft24IJqFPx+xTRM/suw19uXGtGXFUZ316knTkzQFwt6kjVFg7/S0L8J1G+Vo/uCD8DieM1ZGk2WaFaGsrVOdFp1YKCB/iAJFAnR3GFJ6DsPI9UiwsucY1YkbBrVV7MF18Xug/L4ykya7+nxQ0x5iJencHTHwkT14pwfMTdLvZxrLRgxhS/F0q81z+0qWTrx5AS46gTZLlZgHDFSD0rgBE9aZWzZf1x2SxXWKJoY6kpe5WwroRYcyM2ByzXIjrHIvtKdQPmJswzGEFq+/okWw4v5EHdrPd81WLpc6s4ilas6bWjcCObRRux2WA5iS530Xv/G8snacohl21dZ20+L66fzP44410V48kQPcy2DIiDdy1rzj8iRDbn+DHVidy2CDd4Grhhw9J8of59HxWxd02FE7AAlzvsiDdcvKxvzE2fxeBVJCYatfnL+fn7ptcsqLEYDh6PNZyOunto5J4sJfi5ibYcQ== generated by Keepass2Android"
    ];
  };

  environment.variables.EDITOR = "nvim";

  environment.systemPackages = with pkgs; [
    neovim
    vim
    git
  ];

  services.gnome.gnome-keyring.enable = true;

  fonts = {
    packages = with pkgs; [
      (nerdfonts.override {fonts = ["DroidSansMono"];})
      dejavu_fonts
      noto-fonts
      noto-fonts-cjk
      noto-fonts-emoji
    ];
    fontconfig.defaultFonts = {
      serif = ["Noto Serif" "Source Han Serif"];
      sansSerif = ["Noto Sans" "Source Han Sans"];
    };
  };

  programs.dconf.enable = true;
  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # Enable the OpenSSH daemon.
  services.openssh = {
    enable = true;
    ports = [36969];
    settings = {
      PasswordAuthentication = false;
      PermitRootLogin = "no";
    };
  };

  # Open ports in the firewall.
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # Or disable the firewall altogether.
  # networking.firewall.enable = false;

  nix.settings.auto-optimise-store = true;
  nix = {
    gc = {
      automatic = true;
      dates = "weekly";
      options = "--delete-older-than 7d";
    };
    optimise = {
      automatic = true;
      dates = ["weekly"];
    };
  };

  system = {
    # This option defines the first version of NixOS you have installed on this particular machine,
    # and is used to maintain compatibility with application data (e.g. databases) created on older NixOS versions.
    # Do NOT change this value unless you have manually inspected all the changes it would make to your configuration,
    # and migrated your data accordingly.
    # For more information, see `man configuration.nix` or https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion .
    stateVersion = "23.11"; # Did you read the comment?
    # # autoUpgrade = {
    # enable = true;
    # flake = inputs.self.outPath; # TOFix use flake
    # dates = "weekly";
    # };
  };
}
