-- hyprland.lua
-- Generated by hypr-migrate from: hyprland.conf
-- Hyprland >= 0.55 required — https://wiki.hypr.land/
--
-- MIGRATION SUMMARY:
--   Variables:       5 resolved
--   Config keys:     50 emitted
--   Monitors:        3
--   Keybinds:        77 total, 9 collapsed into loops
--   Window rules:    6 total, 4 merged
--   Workspace rules: 6
--   Exec commands:   5
--   Gestures:        0
--   Warnings:        38  ← search MIGRATION_WARNING
--   Review needed:   2  ← search MIGRATION_NOTE
--
-- IMPORTANT: Verify output against https://wiki.hypr.land/ before use
-- The wiki is the only authoritative reference for Lua syntax.

local terminal = "ghostty +new-window"
local fileManager = "nemo"
local menu = "wofi --show drun --matching multi-contains --insensitive"
local mainMod = "super"
local mehMod = "super + ctrl + shift"

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")

hl.config({
    general = {
        allow_tearing = false,
        border_size = 1,
        col.active_border = "rgba(33ccffee) rgba(00ff99ee) 45deg",
        col.inactive_border = "rgba(595959aa)",
        gaps_in = 5,
        gaps_out = "0,15,12",
        layout = "dwindle",
        resize_on_border = true,
    },
    decoration = {
        active_opacity = 1.0,
        blur = {
            enabled = false,
            passes = 1,
            size = 3,
        },
        inactive_opacity = 1.0,
        rounding = 8,
        rounding_power = 2,
        shadow = {
            color = "rgba(1a1a1aee)",
            enabled = true,
            range = 4,
            render_power = 3,
        },
    },
    input = {
        follow_mouse = 1,
        kb_layout = "de",
        kb_model = "",
        kb_options = "caps:escape,compose:rctrl",
        kb_rules = "",
        kb_variant = "nodeadkeys",
        mouse_refocus = false,
        sensitivity = 0.3,
    },
    misc = {
        col.splash = "rgba(00000000)",
        disable_hyprland_logo = false,
        focus_on_activate = true,
        force_default_wallpaper = 0,
        key_press_enables_dpms = true,
    },
    cursor = {
        no_warps = true,
    },
    dwindle = {
        preserve_split = true,
    },
    master = {
        new_status = "master",
    },
    animations = {
        enabled = false,
    },
    -- MIGRATION_WARNING: Conflicting value for .bindel: ',XF86MonBrightnessDown, exec, brightnessctl s 10%-' (line 276) vs ',XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 3%+' (line 270)
    bindel = ",XF86MonBrightnessDown, exec, brightnessctl s 10%-",
    ecosystem = {
        no_donation_nag = true,
    },
    -- MIGRATION_WARNING: Conflicting value for .submap: 'reset' (line 329) vs 'wallpaper' (line 286)
    submap = "reset",
})

hl.monitor({ output = "HDMI-A-2", position = "auto" })
hl.monitor({ output = "DP-5", position = "auto-left" })
-- MIGRATION_NOTE: Empty monitor output — Hyprland may ignore this entry
hl.monitor({ output = "", position = "auto" })

hl.workspace_rule({ workspace = "f[1]", gaps_in = 0, gaps_out = 0 })
hl.workspace_rule({ workspace = "2", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "7", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "8", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "9", monitor = "HDMI-A-2" })
hl.workspace_rule({ workspace = "10", monitor = "HDMI-A-2" })

-- PATTERN: MERGED with line 342
hl.window_rule({
    match = { match:class .* },
    suppress_event = "maximize",
    no_focus = true,
    workspace = "8",
    silent = true,
    workspace = "9",
    silent = true,
    workspace = "10",
})
hl.window_rule({ match = { class = "tile on" }, workspace = "7" })

hl.bind("super + D", function()
    hl.exec_cmd("wofi --show drun --matching multi-contains --insensitive")
end)
hl.bind("super + return", function()
    hl.exec_cmd("ghostty +new-window")
end)
hl.bind("super + E", function()
    hl.exec_cmd("nemo")
end)
hl.bind("super + ctrl + shift + Q", hl.dsp.killactive())
hl.bind("super + ctrl + shift + K", hl.dsp.forcekillactive())
hl.bind("super + V", hl.dsp.togglefloating())
hl.bind("super + H", hl.dsp.movefocus({ l }))
hl.bind("super + L", hl.dsp.movefocus({ r }))
hl.bind("super + K", hl.dsp.movefocus({ u }))
hl.bind("super + J", hl.dsp.movefocus({ d }))
hl.bind("super SHIFT + H", hl.dsp.movecurrentworkspacetomonitor({ l }))
hl.bind("super SHIFT + L", hl.dsp.movecurrentworkspacetomonitor({ r }))
hl.bind("super SHIFT + left", hl.dsp.movewindow({ l }))
hl.bind("super SHIFT + right", hl.dsp.movewindow({ r }))
hl.bind("super SHIFT + up", hl.dsp.movewindow({ u }))
hl.bind("super SHIFT + down", hl.dsp.movewindow({ d }))
-- PATTERN: 10 sequential binds collapsed to loop
for i = 1, 10 do
    hl.bind("super + " .. (i % 10), hl.dsp.focus({ workspace = tostring(i % 10) }))
end

hl.bind("super SHIFT + 1", hl.dsp.movetoworkspacesilent({ 1 }))
hl.bind("super SHIFT + 2", hl.dsp.movetoworkspacesilent({ 2 }))
hl.bind("super SHIFT + 3", hl.dsp.movetoworkspacesilent({ 3 }))
hl.bind("super SHIFT + 4", hl.dsp.movetoworkspacesilent({ 4 }))
hl.bind("super SHIFT + 5", hl.dsp.movetoworkspacesilent({ 5 }))
hl.bind("super SHIFT + 6", hl.dsp.movetoworkspacesilent({ 6 }))
hl.bind("super SHIFT + 7", hl.dsp.movetoworkspacesilent({ 7 }))
hl.bind("super SHIFT + 8", hl.dsp.movetoworkspacesilent({ 8 }))
hl.bind("super SHIFT + 9", hl.dsp.movetoworkspacesilent({ 9 }))
hl.bind("super SHIFT + 0", hl.dsp.movetoworkspacesilent({ 10 }))
hl.bind("super + tab", hl.dsp.focuscurrentorlast())
-- MIGRATION_WARNING: Bind conflict for 'super, asciicircum': 'moveworkspacetomonitor 2 HDMI-A-2' (line 250) vs 'workspace 2' (line 251)
-- MIGRATION_WARNING: Bind conflict for 'super, asciicircum': 'moveworkspacetomonitor 2 HDMI-A-2' (line 250) vs 'workspace 2' (line 320)
hl.bind("super + asciicircum", hl.dsp.moveworkspacetomonitor({ "2 HDMI-A-2" }))
-- MIGRATION_WARNING: Bind conflict for 'super, asciicircum': 'workspace 2' (line 251) vs 'moveworkspacetomonitor 2 HDMI-A-2' (line 250)
hl.bind("super + asciicircum", hl.dsp.focus({ workspace = "2" }))
hl.bind("super + ctrl + shift + F", hl.dsp.fullscreen())
hl.bind("super + ctrl + shift + G", hl.dsp.fullscreen({ 1 }))
hl.bind("super + ctrl + shift + H", hl.dsp.fullscreenstate({ "0 2" }))
hl.bind("super + P", function()
    hl.exec_cmd("grim -g "$(slurp)" - | swappy -f -")
end)
hl.bind("super + mouse:272", hl.dsp.movewindow()), { mouse = true }
hl.bind("super + mouse:273", hl.dsp.resizewindow()), { mouse = true }
hl.bind(" + XF86AudioNext", function()
    hl.exec_cmd("playerctl next")
end), { locked = true }
hl.bind(" + XF86AudioPause", function()
    hl.exec_cmd("playerctl play-pause")
end), { locked = true }
hl.bind(" + XF86AudioPlay", function()
    hl.exec_cmd("playerctl play-pause")
end), { locked = true }
hl.bind(" + XF86AudioPrev", function()
    hl.exec_cmd("playerctl previous")
end), { locked = true }
hl.bind("super + ctrl + shift + W", hl.dsp.submap({ wallpaper }))
-- MIGRATION_WARNING: Bind conflict for ', E': 'exec hyprctl hyprpaper wallpaper' (line 287) vs 'exit ' (line 304)
hl.bind(" + E", function()
    hl.exec_cmd("hyprctl hyprpaper wallpaper")
end)
hl.bind(" + D", function()
    hl.exec_cmd("hyprctl hyprpaper wallpaper")
end)
-- MIGRATION_WARNING: Bind conflict for ', R': 'exec hyprpaper-random' (line 289) vs 'exec reboot' (line 308)
hl.bind(" + R", function()
    hl.exec_cmd("hyprpaper-random")
end)
hl.bind(" + plus", function()
    hl.exec_cmd("hyprpaper-random p")
end)
hl.bind(" + minus", function()
    hl.exec_cmd("hyprpaper-random m")
end)
-- MIGRATION_WARNING: Bind conflict for ', S': 'exec hyprctl hyprpaper wallpaper' (line 292) vs 'exec hyprctl dispatch submap reset && systemctl suspend' (line 306)
hl.bind(" + S", function()
    hl.exec_cmd("hyprctl hyprpaper wallpaper")
end)
hl.bind(" + F", function()
    hl.exec_cmd("sleep 0.1; hyprctl dispatch dpms off HDMI-A-2; sleep 1; hyprctl dispatch dpms on HDMI-A-2")
end)
hl.bind(" + escape", hl.dsp.submap({ reset }))
hl.bind("super + O", hl.dsp.submap({ lock }))
hl.bind(" + O", function()
    hl.exec_cmd("sleep 0.1 && hyprctl --batch "dispatch submap reset ; dispatch dpms off" && swaylock")
end), { repeating = true }
hl.bind(" + X", function()
    hl.exec_cmd("sleep 0.1 && hyprctl --batch "dispatch submap reset ; dispatch dpms off"")
end), { repeating = true }
-- MIGRATION_WARNING: Bind conflict for ', E': 'exit ' (line 304) vs 'exec hyprctl hyprpaper wallpaper' (line 287)
-- MIGRATION_NOTE: hl.dsp.exit() is not available in Lua; use uwsm stop instead (see wiki)
-- MIGRATION_NOTE: hl.dsp.exit() is not available; use uwsm stop instead
-- was: bind = , E, exit, 
hl.bind(" + P", function()
    hl.exec_cmd("poweroff")
end)
-- MIGRATION_WARNING: Bind conflict for ', S': 'exec hyprctl dispatch submap reset && systemctl suspend' (line 306) vs 'exec hyprctl hyprpaper wallpaper' (line 292)
hl.bind(" + S", function()
    hl.exec_cmd("hyprctl dispatch submap reset && systemctl suspend")
end)
-- MIGRATION_WARNING: Bind conflict for ', R': 'exec reboot' (line 308) vs 'exec hyprpaper-random' (line 289)
hl.bind(" + R", function()
    hl.exec_cmd("reboot")
end)
hl.bind(" + catchall", hl.dsp.submap({ reset }))
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'exec hyprctl keyword cursor:no_warps false' (line 315) vs 'submap no-binds' (line 316)
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'exec hyprctl keyword cursor:no_warps false' (line 315) vs 'exec hyprctl keyword cursor:no_warps true' (line 327)
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'exec hyprctl keyword cursor:no_warps false' (line 315) vs 'submap reset' (line 328)
hl.bind("super + ctrl + shift + P", function()
    hl.exec_cmd("hyprctl keyword cursor:no_warps false")
end)
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'submap no-binds' (line 316) vs 'exec hyprctl keyword cursor:no_warps false' (line 315)
hl.bind("super + ctrl + shift + P", hl.dsp.submap({ "no-binds" }))
hl.bind("super + tab", hl.dsp.focuscurrentorlast())
hl.bind("super + asciicircum", hl.dsp.moveworkspacetomonitor({ "2 HDMI-A-2" }))
-- MIGRATION_WARNING: Bind conflict for 'super, asciicircum': 'workspace 2' (line 320) vs 'moveworkspacetomonitor 2 HDMI-A-2' (line 250)
hl.bind("super + asciicircum", hl.dsp.focus({ workspace = "2" }))
hl.bind(" + XF86AudioRaiseVolume", function()
    hl.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 3%+")
end), { longpress = true }
hl.bind(" + XF86AudioLowerVolume", function()
    hl.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-")
end), { longpress = true }
hl.bind(" + F12", function()
    hl.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-")
end), { longpress = true }
hl.bind(" + XF86AudioMute", function()
    hl.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle")
end), { longpress = true }
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'exec hyprctl keyword cursor:no_warps true' (line 327) vs 'exec hyprctl keyword cursor:no_warps false' (line 315)
hl.bind("super + ctrl + shift + P", function()
    hl.exec_cmd("hyprctl keyword cursor:no_warps true")
end)
-- MIGRATION_WARNING: Bind conflict for 'super + ctrl + shift, P': 'submap reset' (line 328) vs 'exec hyprctl keyword cursor:no_warps false' (line 315)
hl.bind("super + ctrl + shift + P", hl.dsp.submap({ reset }))

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("systemctl --user start hypridle.service &")
    hl.exec_cmd("systemctl --user start hyprland-ipc.service &")
end)
