{pkgs, ...}: {
  nix.settings.trusted-users = ["stefan"];

  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.stefan = {
    isNormalUser = true;
    description = "Stefan";
    extraGroups = ["wheel" "networkmanager" "input" "audio" "video" "scanner" "lp" "plugdev"];
    packages = with pkgs; [];
    # shell = pkgs.nushell;
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrOG3FrTlVDOj5TTe5njEB5JUgJ8jum7GdXGK3wNTMeqogCBd1X0K7vTCw2GikgWeUzjN1BM4WeSIlcjyQWGePIVzUlFUhj98h3N9jsQ6T1W7Gyq6vOF35w3cDQTmLYHgFWeDl0llJzj8PW4iJGhVClaVZSyhEVhc78d8xOLadaDK9IljIHaULgDYcZg4Gx+TwcnNmYRvg9oY5RdPft24IJqFPx+xTRM/suw19uXGtGXFUZ316knTkzQFwt6kjVFg7/S0L8J1G+Vo/uCD8DieM1ZGk2WaFaGsrVOdFp1YKCB/iAJFAnR3GFJ6DsPI9UiwsucY1YkbBrVV7MF18Xug/L4ykya7+nxQ0x5iJencHTHwkT14pwfMTdLvZxrLRgxhS/F0q81z+0qWTrx5AS46gTZLlZgHDFSD0rgBE9aZWzZf1x2SxXWKJoY6kpe5WwroRYcyM2ByzXIjrHIvtKdQPmJswzGEFq+/okWw4v5EHdrPd81WLpc6s4ilas6bWjcCObRRux2WA5iS530Xv/G8snacohl21dZ20+L66fzP44410V48kQPcy2DIiDdy1rzj8iRDbn+DHVidy2CDd4Grhhw9J8of59HxWxd02FE7AAlzvsiDdcvKxvzE2fxeBVJCYatfnL+fn7ptcsqLEYDh6PNZyOunto5J4sJfi5ibYcQ== generated by Keepass2Android"
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC12hmjJOAmv64adTvCSsKzkblw/Rh5f35het0PI5wEbwVMf9kBcnEzeLOlP1yQrE5L0iL5N9lZbk3U82SEQ/sZSMvbvTyYEFQ42ylU7BdbIe9+F+qg3suwdcA/Dwz3wVSHabKRHH4F0pjLCTVwG2sA5EhaXU163CF1IkP4DmEyX1nDq42+GBQ/fX2XETJtrHJC6slTSXw3+ykRwnPLMhOmee+4WyCY1B3Xwd14GkM9Yt7FYYRKt/Jc1o2OBGnVlA8d5kDLr2F0gnp8LECWs00KLsdwTR0IOFIiSDkfcJo6kUH2k0q1DcI9xsyBZbuYiXT3XC15PNx+3m6uVLSr4CmAO1gpbxjWcmoGrX4k20G+U+bmShrmJDLvcsKbMFVHyGqYF3KfUahnLMzYMXIJxgeTY0Kj/Km324jBGXr9/jRjysi/Ln8q6APKqnBzpYub7H8r6Jm/mjpLarvFOkBbNKCbDF6xt08vefPL+mba59P9TQCkGp/mQ2tYzJxLPTpQxTX7xxczpsroxHRuqke2bzIjdoCYiAAuM0vEs6DD3o/yGyP55CEAcEr3RDOxP9qP6kXnUEvN2JkQoIYbL3fCIIN/ozD7jU9RSxkJgKbp+jc/AYwpX2vJZnIeI/+HgrgGZFxq8B0SCZQVHd4JzVuQuw3X47CEtpvyt9RRekpCtPkfFQ== generated by Keepass2Android"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINH9SWAyoJv7govQkrJRcir2uMV9b8fO+87Y8oN8IJXL ssh key from raspberrypi to fujitsu"
    ];
  };
}
