{pkgs, ...}: {
  # Define a user account. Don't forget to set a password with ‘passwd’.
  users.users.stefan = {
    isNormalUser = true;
    description = "Stefan";
    extraGroups = ["wheel" "networkmanager" "input" "audio" "video" "scanner" "lp"];
    packages = with pkgs; [];
    # shell = pkgs.nushell;
    shell = pkgs.bash;
    openssh.authorizedKeys.keys = [
      "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCrOG3FrTlVDOj5TTe5njEB5JUgJ8jum7GdXGK3wNTMeqogCBd1X0K7vTCw2GikgWeUzjN1BM4WeSIlcjyQWGePIVzUlFUhj98h3N9jsQ6T1W7Gyq6vOF35w3cDQTmLYHgFWeDl0llJzj8PW4iJGhVClaVZSyhEVhc78d8xOLadaDK9IljIHaULgDYcZg4Gx+TwcnNmYRvg9oY5RdPft24IJqFPx+xTRM/suw19uXGtGXFUZ316knTkzQFwt6kjVFg7/S0L8J1G+Vo/uCD8DieM1ZGk2WaFaGsrVOdFp1YKCB/iAJFAnR3GFJ6DsPI9UiwsucY1YkbBrVV7MF18Xug/L4ykya7+nxQ0x5iJencHTHwkT14pwfMTdLvZxrLRgxhS/F0q81z+0qWTrx5AS46gTZLlZgHDFSD0rgBE9aZWzZf1x2SxXWKJoY6kpe5WwroRYcyM2ByzXIjrHIvtKdQPmJswzGEFq+/okWw4v5EHdrPd81WLpc6s4ilas6bWjcCObRRux2WA5iS530Xv/G8snacohl21dZ20+L66fzP44410V48kQPcy2DIiDdy1rzj8iRDbn+DHVidy2CDd4Grhhw9J8of59HxWxd02FE7AAlzvsiDdcvKxvzE2fxeBVJCYatfnL+fn7ptcsqLEYDh6PNZyOunto5J4sJfi5ibYcQ== generated by Keepass2Android"
      "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINH9SWAyoJv7govQkrJRcir2uMV9b8fO+87Y8oN8IJXL ssh key from raspberrypi to fujitsu"
    ];
  };
}
