# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
[\ue0b2](peach)\
$directory\
[\ue0b0](peach) \
$git_branch\
$git_commit\
${custom.git_tags}\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$elixir\
$erlang\
$golang\
$lua\
$nodejs\
$ocaml\
$php\
$python\
$rust\
$zig\
$nix_shell\
$direnv\
$cmd_duration\
$fill\
$time\
$line_break\
$jobs\
$battery\
$os\
$container\
$shell\
$status\
$character"""

add_newline = true

palette = "custom"

[palettes.custom]
peach = "#fcd4bd"
base = "#304a59"
highlight = "#24773f"
adjacent = "#0000ff"

[character]
error_symbol = '[❯](bold red)'

[directory]
truncate_to_repo = false
truncation_length = 100
read_only = " 🔒"
style = "bold highlight bg:peach"
read_only_style = "red bg:peach"
repo_root_style = 'bold adjacent bg:peach'
before_repo_root_style = 'base bg:peach'
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
use_logical_path = false

[directory.substitutions]
'~/repositories/exg/app/ers' = 'ers'

[direnv]
# disabled = false

[git_branch]
symbol = ''
style = 'purple'
only_attached = true
# ignore_branches = ['master', 'main', 'development']

[git_commit]
style = 'purple'

[custom.git_tags]
description = "Output the current git tags"
command = "git tag --points-at | paste -s -d ' '"
symbol = ' '
format = '[($symbol\($output\) )]($style)'
style = 'purple'
# Only when inside git repository
when = "git rev-parse --is-inside-work-tree >/dev/null 2>&1"

[git_metrics]
disabled = false

[git_status]
stashed = ''
modified = '*'

[python]
symbol = " "

[nix_shell]
symbol = "󱄅 "

[shlvl]
disabled = false
threshold = 2
symbol = "↕"

[os]
disabled = true
symbols.Ubuntu = " "
symbols.NixOS = " "

[shell]
disabled = false
bash_indicator = ""

[status]
disabled = false
format = '[\($symbol$status\) ]($style)'
symbol = ""

[fill]
symbol = " "

[time]
disabled = false
format = '[$time]($style)'
style = 'yellow'
